# Used to speed up the split over time by reusing git's objects
cache_dir: ".gitsplit/split_lesson"

# Path to the repository to split (default = current path)
project_dir: .

# List of splits.
splits:
  - prefix: "lib1"
    target: "git@github.com:anabeto93/split_lib1.git"
  - prefix: "lib2"
    target: "git@github.com:anabeto93/split_lib2.git"

# List of references to split (defined as regexp)
origins:
  - ^master$
  - ^demo$